# Generated by Django 5.1.4 on 2024-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "user_id",
                    models.CharField(
                        max_length=256, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=256, null=True)),
                ("avatar", models.URLField(blank=True, max_length=256, null=True)),
                ("votes", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "candidates",
            },
        ),
    ]
